In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from mpl_toolkits.mplot3d import Axes3D
from matplotlib import cm
from sklearn.linear_model import LogisticRegression
%matplotlib notebook

In [24]:
#data = np.load('/Users/Frances/Documents/seas-fellowship/rvr/data/runp1_2/run_p1_2.npz')
#data = np.load('/Users/Frances/Documents/seas-fellowship/rvr/data/runp1_2/run_p1_2_042219.npz')
#data = np.load('/Users/Frances/Documents/seas-fellowship/rvr/data/runagree/run_agree_p1_2_042019.npz')
#data = np.load('/Users/Frances/Documents/seas-fellowship/rvr/data/runagree/run_agree_interact_042919_prod_thresh.npz')

data = np.load('/Users/Frances/Documents/seas-fellowship/rvr/data/runagree/run_agree_interact_050919_prod.npz')




In [25]:
x_train = data['x_train'][data['train_inds']]
y_train = data['y_train'][data['train_inds']]

x_valid = data['x_train'][data['valid_inds']]
y_valid = data['y_train'][data['valid_inds']]

x_test = data['x_test']
y_test = data['y_test']

yidx = 0

In [26]:
x_train.shape

(16000, 30)

In [27]:
n = 5000

In [28]:
modelall = LogisticRegression()
modelall.fit(x_train, y_train[:, yidx])

/Users/Frances/anaconda3/envs/rvr-env/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [29]:
print(1 - modelall.score(x_train, y_train[:,yidx]))
print(1 - modelall.score(x_valid, y_valid[:,yidx]))
print(1 - modelall.score(x_test, y_test[:,yidx]))

0.10368750000000004
0.11224999999999996
0.20040000000000002


In [16]:
modelall.coef_

array([[-0.27172979, -0.12886561, -0.15707084, -0.33562672,  0.05434694,
        -0.11473164, -0.0934289 ,  0.01935156, -0.06823329, -0.02876349,
        -0.33786971, -0.04331712, -0.0040002 ,  0.2134664 , -0.20045496,
        -0.02272399,  0.41574095,  0.29293718, -0.32968168, -0.2296814 ,
        -0.27669161,  0.23483602,  0.19862118, -0.17022299, -0.31908518,
         0.22066462, -0.51181929, -0.01417286,  0.03113997, -0.31580949]])

In [159]:
model0 = LogisticRegression()
model1 = LogisticRegression() 

In [134]:
model0.fit(x_train[:n, :], y_train[:n, yidx])

/Users/Frances/anaconda3/envs/rvr-env/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [120]:
model0.coef_

array([[-1.91628498, -1.42506881,  1.56488135,  2.98891865,  1.71552265,
         1.74695572, -2.16221389,  0.98306163, -1.2708093 ,  2.02369533,
         2.19710523, -2.07709028, -0.68861884,  0.90355319, -0.65265203,
        -0.59577515,  1.98183885,  1.30805942,  2.15380522, -0.56604378,
        -1.59911531, -2.42837439,  2.38934623, -0.39033674,  1.0966025 ,
        -2.60248476,  0.48132315, -2.45358317,  1.03129185, -1.64417306]])

In [135]:
model1.fit(x_train[n:2*n, :], y_train[n:2*n, yidx])

/Users/Frances/anaconda3/envs/rvr-env/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [122]:
model1.coef_

array([[-1.90205686, -2.11447326,  1.18435923,  2.38442298,  0.20505874,
         1.85896637, -2.05388745,  0.86693443, -0.16057707,  1.79444242,
         1.98731217, -1.94583352, -0.80810388,  1.3910351 , -0.71486058,
        -0.94698966,  1.90083443,  1.54730408,  1.77946153, -0.67011745,
        -2.65849144, -2.30079529,  2.40014367, -0.67432477,  0.0581066 ,
        -1.86042119,  0.59453224, -2.29017489,  1.21538008, -1.56699043]])

In [136]:
model2=LogisticRegression()
model2.fit(x_train[2*n:3*n, :], y_train[2*n:3*n, yidx])

/Users/Frances/anaconda3/envs/rvr-env/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [137]:
model3=LogisticRegression()
model3.fit(x_train[3*n:4*n, :], y_train[3*n:4*n, yidx])

model4=LogisticRegression()
model4.fit(x_train[4*n:5*n, :], y_train[4*n:5*n, yidx])

/Users/Frances/anaconda3/envs/rvr-env/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/Users/Frances/anaconda3/envs/rvr-env/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [138]:
print(model0.score(x_train[2*n:3*n, :], y_train[2*n:3*n, yidx]))
model0.score(x_test, y_test[:,yidx])

0.9128


0.8942

In [140]:
model1.score(x_test, y_test[:,yidx])

0.9402

In [87]:
df = pd.DataFrame({'model0': model0.coef_[0], 'model1' : model1.coef_[0], 'model2': model2.coef_[0], 'model3': model3.coef_[0], 'model4': model4.coef_[0], 'modelall' : modelall.coef_[0]} )

In [29]:
df

model0    model1    model2    model3    model4  modelall
0  -2.157256 -1.265471 -2.986540 -1.033625 -1.413202 -0.517717
1   1.049493  1.186508  1.494112  1.184767  1.391719  0.443307
2  -0.913955 -0.976421 -1.112448 -0.751973 -0.947623 -0.289375
3   2.446023  2.056281  2.609376  2.015693  1.661778  0.802831
4  -1.922294 -2.343310 -1.646182 -2.160539 -1.417754 -0.357486
5  -1.877193 -1.985509 -1.540184 -2.676001 -1.370392 -0.660644
6   1.016347  1.050752  0.877578  1.059801  0.881783  0.315481
7   2.207220  0.599636  1.523612  1.026808  0.864944  0.412457
8  -0.243076 -1.635569 -1.098240 -1.924484 -1.894604 -0.732040
9  -1.824103 -1.940112 -2.107938 -1.907415 -1.940553 -0.699948
10 -2.383822 -2.208405 -1.167493 -0.419752 -1.710749 -0.570504
11 -1.682932 -0.679177 -0.603008 -1.665721 -0.572460 -0.312818
12 -0.473534 -0.680636 -0.654010 -0.442560 -0.766281 -0.292533
13  3.408405  3.212180  1.752316  1.904514  2.252874  0.744066
14  1.954324  1.990873  2.389426  2.087300  2.186550  0.796212
15 -1.281840 -1.508549 -1.783722 -1.627115 -1.671246 -0.678837
16  1.934185  2.288038  2.381226  2.256141  2.227727  0.869155
17 -0.417949 -0.259701 -0.829576 -0.511170 -0.823007 -0.495091
18 -1.237144 -1.351448 -1.393663 -1.200295 -1.244513 -0.288082
19 -1.105719 -1.169465 -1.646444 -1.398063 -1.410626 -0.568085
20  1.155392  1.615917  1.352153  1.537629  1.137328  0.354503
21  1.710973  1.608494  1.735613  1.412366  1.639462  0.427040
22  0.037873  0.258398  0.115593  0.197402  0.099541  0.059584
23  0.352728  0.094512  0.571540  0.074167  0.494420  0.202440
24  0.513807 -0.513069 -1.137620  0.046312 -1.036968 -0.358975
25  1.783294  2.595278  1.919843  2.280223  1.911105  0.674463
26  2.475942  2.878759  2.538366  2.712320  2.301237  0.760306
27 -1.703904 -2.288160 -1.986771 -2.621254 -1.842226 -0.800346
28  1.266376 -0.325488  0.875276  1.601524  0.022912  0.456415
29  0.334030  0.784628  0.548734  0.341139  0.413898  0.067418

In [ ]:
0
3?
4
5?
7
8
10
11
13
17?
23?
24
25?
28


In [105]:
#newx = x_train[:, [1,2,6,9,12,14,15,16,18,19,20,21,22,26,27,29] ] #  [1,2,3, 5, 6,9,12,14,15,16,17, 18,19,20,21,22,23, 25, 26,27,29]

commons_in_r = [1,3,6,7,8,11,12,13,15,16,17,18,19,22,23,24,26,28,29,30]
commons = [x - 1 for x in commons_in_r]

newx = x_train[:, commons]

In [144]:
testm = LogisticRegression()
testm.fit(newx, y_train[:,yidx])

/Users/Frances/anaconda3/envs/rvr-env/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [107]:
#newtestx = x_test[:, [1,2,6,9,12,14,15,16,18,19,20,21,22,26,27,29]]
newtestx = x_test[:, commons]

In [145]:
testm.score(newtestx, y_test[:, yidx])

0.8634

In [48]:
np.sum(model0.coef_[0, [1,2,6,9,12,14,15,16,18,19,20,21,22,26,27,29] ])

3.1283603466930456

In [50]:
np.sum(model0.coef_[0, [0, 3 ,4,5,7,8,10,11,13,17,23,24,25,28] ])

1.293329694872702

In [146]:
for i in range(30):
    print(i+1, modelall.coef_[0][i])

1 0.6279396831206886
2 0.5254375154620301
3 -0.42717525120720645
4 -0.7810646533477356
5 -0.17737257779438756
6 -0.9567401650638161
7 0.8339878789359058
8 -0.324242032112478
9 0.20804226721294808
10 -0.8067515705468277
11 -0.5358812373482886
12 0.5033566472796729
13 0.45295785307660785
14 -0.19867034171365408
15 0.2633784060918376
16 0.4733869391639459
17 -0.5773601593710653
18 -0.6780124417691262
19 -0.7806454857223932
20 0.47369716813376184
21 0.6036914651443545
22 0.7246702398252867
23 -0.6437538450378665
24 0.2625302279575319
25 -0.2435986607435295
26 0.5371255625242419
27 -0.3243844104376237
28 0.7777298664477355
29 -0.5365463661966251
30 0.46764856756716033
